animals = [
    [ "Arlo", "Cole", 18, False ],
    [ "Grier", "Dai", 15, False ],
    [ "Blue Ivy", "Damato", 8, False ],
    [ "Coco", "Dempsey", 19, True ],
    [ "Jett", "Ezell", 4, True ],
    [ "Halycon", "Fossitt", 17, True ],
    [ "Finley", "Giacomin Sanou", 5, True ],
    [ "Mavi", "Groner", 1, True ],
    [ "Scout", "Guo", 7, True ],
    [ "Tallulah", "Haller", 12, False ],
    [ "ZuZu", "Hand", 20, True ],
    [ "Jagger", "Kley", 2, False ],
    [ "Luna", "McWhirter", 10, True ],
    [ "Broncs", "Mekonnen", 6, True ],
    [ "Harlow", "Meng", 11, False ],
    [ "Struggle Bus", "Miller", 16, True ],
    [ "Bubaclat", "Montanaro", 13, False ],
    [ "Ratchet", "Neiman-Golden", 14, False ],
    [ "Googlical", "Nelson", 3, False ],
    [ "Shizzle", "Olivas", 9, False ],
    [ "Menusha", "Omizo", 19, True ],
    [ "Double Rainbow", "Parker", 6, False ],
    [ "Cougar", "Rehorst", 8, True ],
    [ "Trout", "Roepke", 4, True ],
    [ "Poképace", "Schmidt", 2, True ],
    [ "Hurdy-Gurdy", "Schultz", 16, False ],
    [ "Bosky", "Schwantes", 5, True ],
    [ "Boffin", "Strasser", 10, True ],
    [ "Comity", "Tobin", 9, False ],
    [ "Dulcinea", "Wellman", 12, False ],
    [ "Posy", "Yang", 7, False ],
    [ "Epitome", "Ylvisaker", 11, True ],
    [ "Guile", "Zamora", 20, False ],
    [ "Mrs. Fussbudget", "Zhou", 3, True ]
]